#!/usr/bin/env bash
set -x
curl -X POST -F messages=@messages.ndjson https://studio.cucumber.io/api/cucumber_messages\?living_documentation_id\=$1 -H 'accept: application/vnd.api+json; version=1' -H "access-token: $cs_access_token" -H "uid: $csuid" -H "client: $cs_client_token"
